Preparing documents...
Running ROUGE...
Preparing documents...
Running ROUGE...
perl /home/avinesh/.files2rouge/ROUGE-1.5.5.pl -e /home/avinesh/.files2rouge/data -c 95 -r 1000 -n 2 -a -m /tmp/tmp45in_lha/rouge_conf.xml
Preparing documents...
Running ROUGE...
perl /home/avinesh/.files2rouge/ROUGE-1.5.5.pl -e /home/avinesh/.files2rouge/data -c 95 -r 1000 -n 2 -a -m /tmp/tmpi7p5igfu/rouge_conf.xml
Preparing documents...
Running ROUGE...
